#!/usr/bin/env python3
"""
Salty Bot — Voice-friendly Matrix capture bot for Second Brain

Trigger word is "salty" (case-insensitive) as the first word of any message.
Designed for voice-to-text: no slash commands, natural language triggers.

  salty <anything>   — open a capture session (or start fresh if one is active)
  salty done         — save session to second_brain.ideas
  salty cancel       — discard session without saving
  salty status       — show current mode and session contents

While a session is open, any message (text, image, video) is accumulated.
Sessions autosave after SALTY_AUTOSAVE_MINUTES of inactivity (default: 10).

When VAULT_ROLE_ID_FILE is set (Vault AppRole mode), all secrets are fetched
from Vault at startup instead of being baked into the systemd environment:
    VAULT_ADDR           — Vault address
    VAULT_ROLE_ID_FILE   — path to role-id credential file
    VAULT_SECRET_ID_FILE — path to secret-id credential file

Vault paths (KV v2, all under kv/data/):
    runtime/<VAULT_BOT_HOST>/<VAULT_BOT_NAME>/mongodb   → uri           (generated by mongodb configure)
    runtime/<VAULT_BOT_HOST>/<VAULT_BOT_NAME>/rustfs    → access_key, secret_key  (generated by rustfs configure)
    infrastructure/mylab/anthropic                       → api_key       (imported from LabSecrets.yml)
    infrastructure/<VAULT_MATRIX_HOST>/synapse/bots/<matrix_localpart> → password (imported from LabSecrets.yml)

Env vars controlling Vault paths (set by systemd template):
    VAULT_BOT_HOST    — inventory_hostname of this bot's host (default: bot-test)
    VAULT_MATRIX_HOST — inventory_hostname of the Matrix server (default: matrix-web)
    VAULT_BOT_NAME    — Vault runtime path key for this bot (default: salty-bot)

Legacy/non-secret environment variables:
    MATRIX_SALTY_TOKEN      — Bot access token (static, baked at deploy time when Vault mode is off)
    MATRIX_HOMESERVER_URL   — Homeserver URL
    MATRIX_ROOM_ID          — Room ID or alias
    MATRIX_BOT_USER_ID      — Bot Matrix user ID (@salty:domain)
    ANTHROPIC_API_KEY       — Anthropic API key (legacy mode only)
    BRAIN2_MONGODB_URI      — MongoDB URI (legacy mode only)
    BRAIN2_MONGODB_DB       — Database name (default: second_brain)
    MATRIX_ALLOWED_USERS    — Comma-separated allowed sender IDs
    S3_ENDPOINT_URL         — MinIO/S3 endpoint
    S3_ACCESS_KEY           — S3 access key ID (legacy mode only)
    S3_SECRET_KEY           — S3 secret access key (legacy mode only)
    S3_BUCKET               — Bucket name (default: salty-captures)
    SALTY_AUTOSAVE_MINUTES  — Inactivity timeout (default: 10)
"""

import asyncio
import base64
import json
import logging
import os
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    from nio import (
        AsyncClient, MatrixRoom,
        RoomMessageAudio, RoomMessageFile, RoomMessageImage,
        RoomMessageText, RoomMessageVideo,
        SyncError,
    )
except ImportError:
    print("Error: matrix-nio not installed", file=sys.stderr)
    sys.exit(1)

try:
    from anthropic import AsyncAnthropic
except ImportError:
    print("Error: anthropic not installed", file=sys.stderr)
    sys.exit(1)

try:
    from bson import ObjectId
except ImportError:
    print("Error: pymongo not installed", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'common'))
import bot_common

get_db = bot_common.get_db
get_s3 = bot_common.get_s3
ensure_bucket = bot_common.ensure_bucket

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    stream=sys.stderr,
    datefmt='%Y-%m-%d %H:%M:%S',
)
logger = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────────────

ALLOWED_USERS = bot_common.allowed_users()

AUTOSAVE_MINUTES = int(os.getenv('SALTY_AUTOSAVE_MINUTES', '10'))
VISION_MODEL     = "claude-sonnet-4-6"
TEXT_MODEL       = "claude-haiku-4-5-20251001"
BOT_START_MS     = int(time.time() * 1000)

S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL', 'http://localhost:9000')
S3_BUCKET       = os.getenv('S3_BUCKET', 'salty-captures')

_processed_events: set[str] = set()

stats = {
    "sessions_started":   0,
    "sessions_saved":     0,
    "sessions_autosaved": 0,
    "sessions_cancelled": 0,
    "images_captured":    0,
    "videos_captured":    0,
    "api_calls":          0,
    "input_tokens":       0,
    "output_tokens":      0,
}

# ── Session state ─────────────────────────────────────────────────────────────

@dataclass
class CaptureSession:
    sender: str
    intent: str                    # text after "salty" that opened the session
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_activity: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    text_parts: list[str] = field(default_factory=list)
    attachments: list[dict] = field(default_factory=list)
    # each attachment: {type, mxc_url, s3_bucket, s3_key, description}

    def age_minutes(self) -> float:
        return (datetime.now(timezone.utc) - self.started_at).total_seconds() / 60

    def idle_minutes(self) -> float:
        return (datetime.now(timezone.utc) - self.last_activity).total_seconds() / 60

    def autosave_in_minutes(self) -> float:
        return max(0.0, AUTOSAVE_MINUTES - self.idle_minutes())

    def is_empty(self) -> bool:
        return not self.text_parts and not self.attachments

    def to_dict(self) -> dict:
        return {
            "_id":           self.sender,
            "intent":        self.intent,
            "started_at":    self.started_at.isoformat(),
            "last_activity": self.last_activity.isoformat(),
            "text_parts":    self.text_parts,
            "attachments":   self.attachments,
        }

    @classmethod
    def from_dict(cls, doc: dict) -> "CaptureSession":
        s = cls(sender=doc["_id"], intent=doc.get("intent", ""))
        s.started_at    = datetime.fromisoformat(doc["started_at"])
        s.last_activity = datetime.fromisoformat(doc["last_activity"])
        s.text_parts    = doc.get("text_parts", [])
        s.attachments   = doc.get("attachments", [])
        return s

    def content_summary(self) -> str:
        parts = []
        if self.text_parts:
            n = len(self.text_parts)
            parts.append(f"{n} text message{'s' if n != 1 else ''}")
        imgs  = sum(1 for a in self.attachments if a["type"] == "image")
        vids  = sum(1 for a in self.attachments if a["type"] == "video")
        auds  = sum(1 for a in self.attachments if a["type"] == "audio")
        files = sum(1 for a in self.attachments if a["type"] == "file")
        if imgs:
            parts.append(f"{imgs} image{'s' if imgs != 1 else ''}")
        if vids:
            parts.append(f"{vids} video{'s' if vids != 1 else ''}")
        if auds:
            parts.append(f"{auds} voice note{'s' if auds != 1 else ''}")
        if files:
            parts.append(f"{files} file{'s' if files != 1 else ''}")
        return " · ".join(parts) if parts else "nothing yet"


# Active sessions keyed by sender Matrix ID
sessions: dict[str, CaptureSession] = {}

# ── S3 ────────────────────────────────────────────────────────────────────────
# get_s3() / ensure_bucket() now come from bot_common (aliased above).


def upload_to_s3(data: bytes, media_type: str, bucket: str, subdir: str) -> tuple[ObjectId, str]:
    ext_map = {
        "image/jpeg": "jpg", "image/png": "png",
        "image/webp": "webp", "image/gif": "gif",
        "video/mp4": "mp4", "video/webm": "webm", "video/quicktime": "mov",
    }
    ext = ext_map.get(media_type, "bin")
    oid = ObjectId()
    now = datetime.now(timezone.utc)
    key = f"{subdir}/{now.year}/{now.month:02d}/{oid}.{ext}"
    get_s3().put_object(Bucket=bucket, Key=key, Body=data, ContentType=media_type)
    logger.info(f"S3 upload: {bucket}/{key} ({len(data):,} bytes)")
    return oid, key


# ── MongoDB ───────────────────────────────────────────────────────────────────
# get_db() now comes from bot_common (aliased above).


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_idea(session: CaptureSession, title: str, cleaned_text: str,
               tags: list[str], autosaved: bool) -> str | None:
    db = get_db()
    if db is None:
        return None
    doc = {
        "title":        title,
        "intent":       session.intent,
        "text_parts":   session.text_parts,
        "cleaned_text": cleaned_text,
        "attachments":  session.attachments,
        "tags":         tags,
        "sender":       session.sender,
        "captured_at":  session.started_at.isoformat(),
        "saved_at":     _now_iso(),
        "autosaved":    autosaved,
        "source":       "salty-bot",
    }
    result = db.ideas.insert_one(doc)
    logger.info(f"Idea saved: {result.inserted_id} title={title!r}")
    return str(result.inserted_id)


# ── MongoDB session persistence ──────────────────────────────────────────────

def _db_ensure_indexes():
    db = get_db()
    if db is None:
        return
    db.processed_events.create_index("processed_at", expireAfterSeconds=86400)
    logger.info("MongoDB indexes ensured")


def _db_open_session(session: CaptureSession):
    db = get_db()
    if db is None:
        return
    try:
        db.sessions.replace_one({"_id": session.sender}, session.to_dict(), upsert=True)
    except Exception as e:
        logger.error(f"Session open failed: {e}")


def _db_push_text(sender: str, text: str):
    db = get_db()
    if db is None:
        return
    try:
        db.sessions.update_one(
            {"_id": sender},
            {"$push": {"text_parts": text}, "$set": {"last_activity": _now_iso()}},
        )
    except Exception as e:
        logger.error(f"Session text push failed: {e}")


def _db_push_attachment(sender: str, attachment: dict):
    db = get_db()
    if db is None:
        return
    try:
        db.sessions.update_one(
            {"_id": sender},
            {"$push": {"attachments": attachment}, "$set": {"last_activity": _now_iso()}},
        )
    except Exception as e:
        logger.error(f"Session attachment push failed: {e}")


def _db_close_session(sender: str):
    db = get_db()
    if db is None:
        return
    try:
        db.sessions.delete_one({"_id": sender})
    except Exception as e:
        logger.error(f"Session close failed: {e}")


def _db_load_sessions() -> list[CaptureSession]:
    db = get_db()
    if db is None:
        return []
    try:
        return [CaptureSession.from_dict(doc) for doc in db.sessions.find()]
    except Exception as e:
        logger.error(f"Session load failed: {e}")
        return []


# ── Event de-duplication (TTL-backed) ─────────────────────────────────────────

def _db_mark_processed(event_id: str):
    _processed_events.add(event_id)
    db = get_db()
    if db is None:
        return
    try:
        db.processed_events.insert_one({
            "_id":          event_id,
            "processed_at": datetime.now(timezone.utc),
        })
    except Exception:
        pass  # duplicate key = already recorded, fine


def _db_load_processed_events():
    db = get_db()
    if db is None:
        return
    try:
        cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
        for doc in db.processed_events.find({"processed_at": {"$gt": cutoff}}):
            _processed_events.add(doc["_id"])
        logger.info(f"Loaded {len(_processed_events)} processed event IDs from MongoDB")
    except Exception as e:
        logger.error(f"Processed events load failed: {e}")


# ── Claude ────────────────────────────────────────────────────────────────────

async def describe_image(image_bytes: bytes, media_type: str, api_key: str) -> str:
    if media_type not in ("image/jpeg", "image/png", "image/gif", "image/webp"):
        media_type = "image/jpeg"
    b64 = base64.standard_b64encode(image_bytes).decode()
    aclient = AsyncAnthropic(api_key=api_key)
    try:
        resp = await aclient.messages.create(
            model=VISION_MODEL,
            max_tokens=256,
            messages=[{
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {"type": "base64", "media_type": media_type, "data": b64},
                    },
                    {
                        "type": "text",
                        "text": (
                            "Describe what you see in 2-3 sentences for a personal note. "
                            "Focus on content — text, diagrams, objects, people — not aesthetics."
                        ),
                    },
                ],
            }],
        )
        stats["api_calls"]    += 1
        stats["input_tokens"]  += resp.usage.input_tokens
        stats["output_tokens"] += resp.usage.output_tokens
        return resp.content[0].text.strip()
    except Exception as e:
        logger.error(f"Image description failed: {e}")
        return "[image — description unavailable]"


async def process_session(session: CaptureSession, api_key: str) -> tuple[str, str, list[str]]:
    """Clean text, generate title, extract tags. Returns (title, cleaned_text, tags)."""
    if session.is_empty():
        return "Empty note", "", []

    if not api_key:
        title = (session.intent[:50] + "…") if len(session.intent) > 50 else session.intent or "Note"
        return title, "\n".join(session.text_parts), []

    image_lines = [
        f"  - {a['description']}"
        for a in session.attachments
        if a["type"] == "image" and a.get("description")
    ]

    prompt_lines = []
    if session.intent:
        prompt_lines.append(f'Trigger: "{session.intent}"')
    if session.text_parts:
        prompt_lines.append("Voice messages (in order):")
        for i, t in enumerate(session.text_parts, 1):
            prompt_lines.append(f'  {i}. "{t}"')
    if image_lines:
        prompt_lines.append("Images:")
        prompt_lines.extend(image_lines)
    if sum(1 for a in session.attachments if a["type"] == "video") > 0:
        n = sum(1 for a in session.attachments if a["type"] == "video")
        prompt_lines.append(f"Videos: {n} attached (no transcription)")

    prompt = "\n".join(prompt_lines) + """

Fix voice-to-text errors and filler words, generate a short title, extract tags.

Return JSON only — no prose:
{
  "title": "4-8 word title",
  "cleaned_text": "cleaned and readable combined text",
  "tags": ["tag1", "tag2"]
}"""

    aclient = AsyncAnthropic(api_key=api_key)
    try:
        resp = await aclient.messages.create(
            model=TEXT_MODEL,
            max_tokens=512,
            messages=[{"role": "user", "content": prompt}],
        )
        stats["api_calls"]    += 1
        stats["input_tokens"]  += resp.usage.input_tokens
        stats["output_tokens"] += resp.usage.output_tokens

        raw = resp.content[0].text.strip()
        if raw.startswith("```"):
            raw = re.sub(r'^```[a-z]*\n?', '', raw).rstrip('`').strip()
        data = json.loads(raw)
        return data.get("title", "Untitled"), data.get("cleaned_text", ""), data.get("tags", [])
    except Exception as e:
        logger.error(f"Session processing failed: {e}")
        title = (session.intent[:50] + "…") if len(session.intent) > 50 else session.intent or "Note"
        return title, "\n".join(session.text_parts), []


# ── Session save / cancel ─────────────────────────────────────────────────────

async def save_session(sender: str, client: AsyncClient, room_id: str,
                       api_key: str, autosaved: bool = False):
    session = sessions.pop(sender, None)
    if session is None:
        return

    # NOTE: For multi-instance deployments (e.g., team field audits running
    # multiple bot instances), add status:"processing" via update_one here
    # before the Claude/S3 window to prevent concurrent autosave races.
    # Not needed for single-instance deployment.

    if session.is_empty():
        _db_close_session(sender)
        await _send(client, room_id, "Nothing to save — session was empty.")
        return

    await _send(client, room_id, "Saving…")

    title, cleaned_text, tags = await process_session(session, api_key)
    idea_id = write_idea(session, title, cleaned_text, tags, autosaved)

    if idea_id is None:
        # Leave session in MongoDB — user can retry with "salty done" after restart
        await _send(client, room_id, "⚠️ MongoDB unavailable — note not saved. Try again after reconnect.")
        return

    # Only remove from MongoDB after successful idea write
    _db_close_session(sender)

    tag_str  = "  " + "  ".join(f"#{t}" for t in tags) if tags else ""
    verb     = "Autosaved" if autosaved else "Saved"
    reply    = f"**{verb}** — *{title}*\n  {session.content_summary()}{tag_str}"
    await _send(client, room_id, reply)

    if autosaved:
        stats["sessions_autosaved"] += 1
    else:
        stats["sessions_saved"] += 1
    logger.info(f"Session {'autosaved' if autosaved else 'saved'} for {sender}: {idea_id}")


# ── Matrix helpers ────────────────────────────────────────────────────────────

async def _send(client: AsyncClient, room_id: str, body: str):
    try:
        await client.room_send(
            room_id=room_id,
            message_type="m.room.message",
            content={"msgtype": "m.text", "body": body},
        )
    except Exception as e:
        logger.error(f"Send failed: {e}")


def _is_allowed(sender: str) -> bool:
    return not ALLOWED_USERS or sender in ALLOWED_USERS


def _is_stale(event) -> bool:
    return event.server_timestamp < BOT_START_MS or event.event_id in _processed_events


def _mark(event):
    _db_mark_processed(event.event_id)


# ── Text callback ─────────────────────────────────────────────────────────────

async def text_callback(room: MatrixRoom, event: RoomMessageText,
                        client: AsyncClient, bot_user_id: str, api_key: str):
    if event.sender == bot_user_id or _is_stale(event):
        return
    _mark(event)
    if not _is_allowed(event.sender):
        return

    body  = (event.body or "").strip()
    words = body.split()
    if not words:
        return

    # Strip trailing punctuation that voice-to-text might attach to the trigger word
    first = words[0].lower().rstrip('.,!?;:')

    if first != "salty":
        # Not a trigger — accumulate if session is active
        session = sessions.get(event.sender)
        if session is not None:
            session.text_parts.append(body)
            session.last_activity = datetime.now(timezone.utc)
            _db_push_text(event.sender, body)
            logger.info(f"Text accumulated for {event.sender}: {body[:60]!r}")
        return

    # Everything after "salty "
    rest = body[body.lower().find('salty') + 5:].strip()
    cmd  = rest.split()[0].lower().rstrip('.,!?;:') if rest else ""

    if cmd == "done":
        if sessions.get(event.sender) is None:
            await _send(client, room.room_id, "No active capture.")
        else:
            await save_session(event.sender, client, room.room_id, api_key)

    elif cmd == "cancel":
        session = sessions.pop(event.sender, None)
        if session is None:
            await _send(client, room.room_id, "Nothing to cancel.")
        else:
            _db_close_session(event.sender)
            stats["sessions_cancelled"] += 1
            await _send(client, room.room_id,
                        f"Cancelled — {session.content_summary()} discarded.")

    elif cmd == "status":
        session = sessions.get(event.sender)
        if session is None:
            await _send(client, room.room_id, "No active capture.")
        else:
            mins = session.autosave_in_minutes()
            mins_str = f"{mins:.0f} min" if mins >= 1 else "< 1 min"
            await _send(client, room.room_id,
                f"**Active capture** · {session.age_minutes():.0f} min old\n"
                f"  {session.content_summary()}\n"
                f"  Autosaves in ~{mins_str}")

    else:
        # New session trigger — autosave any existing open session first
        existing = sessions.get(event.sender)
        if existing and not existing.is_empty():
            logger.info(f"New trigger over active session for {event.sender} — autosaving first")
            await save_session(event.sender, client, room.room_id, api_key, autosaved=True)

        sessions[event.sender] = CaptureSession(sender=event.sender, intent=rest)
        _db_open_session(sessions[event.sender])
        stats["sessions_started"] += 1
        logger.info(f"Session opened for {event.sender}: {rest!r}")
        await _send(client, room.room_id,
                    "Ready — send text, photos, video, voice notes, or files. Say **salty done** to save.")


# ── Image callback ────────────────────────────────────────────────────────────

async def image_callback(room: MatrixRoom, event: RoomMessageImage,
                         client: AsyncClient, bot_user_id: str, api_key: str):
    if event.sender == bot_user_id or _is_stale(event):
        return
    _mark(event)
    if not _is_allowed(event.sender):
        return

    session = sessions.get(event.sender)
    if session is None:
        return  # no active session — ignore

    await _send(client, room.room_id, "Image received, processing…")

    try:
        resp = await client.download(mxc=event.url)
        if not hasattr(resp, 'body') or not resp.body:
            await _send(client, room.room_id, "⚠️ Could not download image.")
            return
        image_bytes = resp.body
        media_type  = getattr(resp, 'content_type', 'image/jpeg') or 'image/jpeg'
    except Exception as e:
        logger.error(f"Image download failed: {e}")
        await _send(client, room.room_id, f"⚠️ Download failed: {e}")
        return

    try:
        _, s3_key = upload_to_s3(image_bytes, media_type, S3_BUCKET, subdir="images")
    except Exception as e:
        logger.error(f"S3 upload failed: {e}")
        await _send(client, room.room_id, f"⚠️ S3 upload failed: {e}")
        return

    description = await describe_image(image_bytes, media_type, api_key) if api_key else ""

    attachment = {
        "type":        "image",
        "mxc_url":     event.url,
        "s3_bucket":   S3_BUCKET,
        "s3_key":      s3_key,
        "description": description,
    }
    session.attachments.append(attachment)
    _db_push_attachment(event.sender, attachment)
    session.last_activity = datetime.now(timezone.utc)
    stats["images_captured"] += 1

    preview = f"\n  _{description[:80]}{'…' if len(description) > 80 else ''}_" if description else ""
    await _send(client, room.room_id, f"Image saved.{preview}")
    logger.info(f"Image captured for {event.sender}: {s3_key}")


# ── Video callback ────────────────────────────────────────────────────────────

async def video_callback(room: MatrixRoom, event: RoomMessageVideo,
                         client: AsyncClient, bot_user_id: str):
    if event.sender == bot_user_id or _is_stale(event):
        return
    _mark(event)
    if not _is_allowed(event.sender):
        return

    session = sessions.get(event.sender)
    if session is None:
        return

    await _send(client, room.room_id, "Video received, uploading to storage…")

    try:
        resp = await client.download(mxc=event.url)
        if not hasattr(resp, 'body') or not resp.body:
            await _send(client, room.room_id, "⚠️ Could not download video.")
            return
        video_bytes = resp.body
        media_type  = getattr(resp, 'content_type', 'video/mp4') or 'video/mp4'
    except Exception as e:
        logger.error(f"Video download failed: {e}")
        await _send(client, room.room_id, f"⚠️ Download failed: {e}")
        return

    try:
        _, s3_key = upload_to_s3(video_bytes, media_type, S3_BUCKET, subdir="videos")
    except Exception as e:
        logger.error(f"S3 upload failed: {e}")
        await _send(client, room.room_id, f"⚠️ S3 upload failed: {e}")
        return

    attachment = {
        "type":        "video",
        "mxc_url":     event.url,
        "s3_bucket":   S3_BUCKET,
        "s3_key":      s3_key,
        "description": "",
    }
    session.attachments.append(attachment)
    _db_push_attachment(event.sender, attachment)
    session.last_activity = datetime.now(timezone.utc)
    stats["videos_captured"] += 1

    await _send(client, room.room_id, "Video saved.")
    logger.info(f"Video captured for {event.sender}: {s3_key}")


# ── File callback (PDFs, docs, etc.) ─────────────────────────────────────────

async def file_callback(room: MatrixRoom, event: RoomMessageFile,
                        client: AsyncClient, bot_user_id: str):
    if event.sender == bot_user_id or _is_stale(event):
        return
    _mark(event)
    if not _is_allowed(event.sender):
        return

    session = sessions.get(event.sender)
    if session is None:
        return

    filename = getattr(event, 'body', 'file') or 'file'
    await _send(client, room.room_id, f"File received ({filename}), uploading…")

    try:
        resp = await client.download(mxc=event.url)
        if not hasattr(resp, 'body') or not resp.body:
            await _send(client, room.room_id, "⚠️ Could not download file.")
            return
        file_bytes = resp.body
        media_type = getattr(resp, 'content_type', 'application/octet-stream') or 'application/octet-stream'
    except Exception as e:
        logger.error(f"File download failed: {e}")
        await _send(client, room.room_id, f"⚠️ Download failed: {e}")
        return

    try:
        _, s3_key = upload_to_s3(file_bytes, media_type, S3_BUCKET, subdir="files")
    except Exception as e:
        logger.error(f"S3 upload failed: {e}")
        await _send(client, room.room_id, f"⚠️ S3 upload failed: {e}")
        return

    attachment = {
        "type":        "file",
        "filename":    filename,
        "mxc_url":     event.url,
        "s3_bucket":   S3_BUCKET,
        "s3_key":      s3_key,
        "description": "",
    }
    session.attachments.append(attachment)
    _db_push_attachment(event.sender, attachment)
    session.last_activity = datetime.now(timezone.utc)

    await _send(client, room.room_id, f"File saved ({filename}).")
    logger.info(f"File captured for {event.sender}: {s3_key} ({filename})")


# ── Audio callback (voice memos) ─────────────────────────────────────────────

async def audio_callback(room: MatrixRoom, event: RoomMessageAudio,
                         client: AsyncClient, bot_user_id: str):
    if event.sender == bot_user_id or _is_stale(event):
        return
    _mark(event)
    if not _is_allowed(event.sender):
        return

    session = sessions.get(event.sender)
    if session is None:
        return

    filename = getattr(event, 'body', 'audio') or 'audio'
    await _send(client, room.room_id, f"Voice note received ({filename}), saving…")

    try:
        resp = await client.download(mxc=event.url)
        if not hasattr(resp, 'body') or not resp.body:
            await _send(client, room.room_id, "⚠️ Could not download audio.")
            return
        audio_bytes = resp.body
        media_type  = getattr(resp, 'content_type', 'audio/ogg') or 'audio/ogg'
    except Exception as e:
        logger.error(f"Audio download failed: {e}")
        await _send(client, room.room_id, f"⚠️ Download failed: {e}")
        return

    ext_map = {
        "audio/ogg": "ogg", "audio/mpeg": "mp3", "audio/mp4": "m4a",
        "audio/wav": "wav", "audio/webm": "webm", "audio/aac": "aac",
    }
    ext = ext_map.get(media_type, "ogg")
    oid = ObjectId()
    now = datetime.now(timezone.utc)
    s3_key = f"audio/{now.year}/{now.month:02d}/{oid}.{ext}"

    try:
        get_s3().put_object(Bucket=S3_BUCKET, Key=s3_key, Body=audio_bytes, ContentType=media_type)
        logger.info(f"S3 upload: {S3_BUCKET}/{s3_key} ({len(audio_bytes):,} bytes)")
    except Exception as e:
        logger.error(f"S3 upload failed: {e}")
        await _send(client, room.room_id, f"⚠️ S3 upload failed: {e}")
        return

    attachment = {
        "type":        "audio",
        "filename":    filename,
        "mxc_url":     event.url,
        "s3_bucket":   S3_BUCKET,
        "s3_key":      s3_key,
        "transcript":  "",   # populated later if/when transcription is added
        "description": "",
    }
    session.attachments.append(attachment)
    _db_push_attachment(event.sender, attachment)
    session.last_activity = datetime.now(timezone.utc)

    await _send(client, room.room_id, "Voice note saved. Transcription can be added later.")
    logger.info(f"Audio captured for {event.sender}: {s3_key} ({filename})")


# ── Autosave background loop ──────────────────────────────────────────────────

async def autosave_loop(client: AsyncClient, room_id: str, api_key: str):
    while True:
        await asyncio.sleep(60)
        db = get_db()
        if db is not None:
            cutoff = (datetime.now(timezone.utc) - timedelta(minutes=AUTOSAVE_MINUTES)).isoformat()
            expired_docs = list(db.sessions.find({"last_activity": {"$lt": cutoff}}))
            for doc in expired_docs:
                sender = doc["_id"]
                if sender not in sessions:
                    sessions[sender] = CaptureSession.from_dict(doc)
                logger.info(f"Autosave triggered for {sender}")
                await save_session(sender, client, room_id, api_key, autosaved=True)
        else:
            # MongoDB unavailable — fall back to in-memory check
            expired = [s for s, sess in list(sessions.items()) if sess.idle_minutes() >= AUTOSAVE_MINUTES]
            for sender in expired:
                logger.info(f"Autosave (in-memory fallback) for {sender}")
                await save_session(sender, client, room_id, api_key, autosaved=True)


# ── Secrets ───────────────────────────────────────────────────────────────────

def load_vault_credentials(homeserver_url: str, bot_user_id: str) -> None:
    """
    Authenticate via Vault AppRole and inject all secrets into os.environ.
    Called only when VAULT_ROLE_ID_FILE is set. Exits on any failure.

    After this function returns, the following env vars are populated:
        MATRIX_SALTY_TOKEN  — freshly obtained from Matrix login
        ANTHROPIC_API_KEY
        BRAIN2_MONGODB_URI
        S3_ACCESS_KEY, S3_SECRET_KEY

    All other code (get_db, get_s3, _load_secret) reads from os.environ
    unchanged — no other callers need modification.
    """
    logger.info("Vault AppRole mode — fetching credentials from Vault")

    try:
        vault_token = bot_common.vault_approle_auth()
    except Exception as e:
        logger.error(f"Vault AppRole auth failed: {e}")
        sys.exit(1)

    vault_addr = os.getenv('VAULT_ADDR', '').rstrip('/')

    bot_host    = os.getenv('VAULT_BOT_HOST', 'bot-test')
    matrix_host = os.getenv('VAULT_MATRIX_HOST', 'matrix-web')
    bot_name    = os.getenv('VAULT_BOT_NAME', 'salty-bot')

    def _read(path: str) -> dict:
        try:
            return bot_common.vault_kv_read(vault_token, path, vault_addr)
        except Exception as e:
            logger.error(f"Vault read failed — {path}: {e}")
            sys.exit(1)

    # MongoDB — runtime credential (generated by mongodb configure task)
    mongo = _read(f"runtime/{bot_host}/{bot_name}/mongodb")
    os.environ['BRAIN2_MONGODB_URI'] = mongo['uri']
    logger.info("Vault: MongoDB URI loaded")

    # S3 / rustfs — runtime credential (generated by rustfs configure task)
    s3 = _read(f"runtime/{bot_host}/{bot_name}/rustfs")
    os.environ['S3_ACCESS_KEY'] = s3['access_key']
    os.environ['S3_SECRET_KEY'] = s3['secret_key']
    logger.info("Vault: S3 credentials loaded")

    # Anthropic — infrastructure secret (imported from LabSecrets.yml, shared key)
    anthropic_host = os.getenv('VAULT_ANTHROPIC_HOST', 'mylab')
    anthropic = _read(f"infrastructure/{anthropic_host}/anthropic")
    os.environ['ANTHROPIC_API_KEY'] = anthropic['api_key']
    logger.info("Vault: Anthropic API key loaded")

    # Matrix — infrastructure secret; synapse path uses the Matrix localpart (@salty:domain)
    matrix_localpart = bot_user_id.lstrip('@').split(':')[0] if bot_user_id else 'salty'
    matrix = _read(f"infrastructure/{matrix_host}/synapse/bots/{matrix_localpart}")
    matrix_password = matrix['password']
    try:
        access_token = bot_common.matrix_login(homeserver_url, bot_user_id, matrix_password)
    except Exception as e:
        logger.error(f"Matrix login failed: {e}")
        sys.exit(1)
    os.environ['MATRIX_SALTY_TOKEN'] = access_token
    logger.info("Vault: Matrix token obtained via login")


def _load_secret(env_var: str) -> str | None:
    val = os.getenv(env_var)
    if val:
        return val
    secrets_file = Path.home() / '.secrets/LabMatrix'
    if secrets_file.exists():
        prefix = f'export {env_var}='
        for line in secrets_file.read_text().splitlines():
            if line.startswith(prefix):
                return line.split('=', 1)[1].strip().strip('"\'')
    return None


# ── Main ──────────────────────────────────────────────────────────────────────

async def main():
    homeserver_url = os.getenv('MATRIX_HOMESERVER_URL', '')
    room_id        = os.getenv('MATRIX_ROOM_ID', '')
    bot_user_id    = os.getenv('MATRIX_BOT_USER_ID', '')

    if not homeserver_url or not room_id or not bot_user_id:
        logger.error("MATRIX_HOMESERVER_URL, MATRIX_ROOM_ID, MATRIX_BOT_USER_ID are required")
        sys.exit(1)

    # Vault AppRole mode: fetch all secrets before any other initialization
    if os.getenv('VAULT_ROLE_ID_FILE'):
        load_vault_credentials(homeserver_url, bot_user_id)

    token   = _load_secret('MATRIX_SALTY_TOKEN')
    api_key = _load_secret('ANTHROPIC_API_KEY')

    if not token:
        logger.error("MATRIX_SALTY_TOKEN not found — cannot start")
        sys.exit(1)

    db = get_db()
    _db_ensure_indexes()
    _db_load_processed_events()

    try:
        ensure_bucket(S3_BUCKET)
        s3_status = f"✓ ({S3_ENDPOINT_URL}/{S3_BUCKET})"
    except Exception as e:
        s3_status = f"✗ {e}"
        logger.error(f"S3 bucket check failed: {e}")

    print("=" * 72)
    print("Salty Bot")
    print(f"  Homeserver   : {homeserver_url}")
    print(f"  Bot user     : {bot_user_id}")
    print(f"  Room         : {room_id}")
    print(f"  MongoDB      : {'connected' if db is not None else 'UNAVAILABLE'}")
    print(f"  S3           : {s3_status}")
    print(f"  API key      : {'✓' if api_key else '✗ missing (text cleanup disabled)'}")
    print(f"  Autosave     : {AUTOSAVE_MINUTES} min")
    print(f"  Allowed users: {', '.join(ALLOWED_USERS) if ALLOWED_USERS else 'all'}")
    print("=" * 72)

    client = AsyncClient(homeserver_url, bot_user_id)
    client.access_token = token

    async def _text_cb(room, event):
        await text_callback(room, event, client, bot_user_id, api_key)

    async def _image_cb(room, event):
        await image_callback(room, event, client, bot_user_id, api_key)

    async def _video_cb(room, event):
        await video_callback(room, event, client, bot_user_id)

    async def _file_cb(room, event):
        await file_callback(room, event, client, bot_user_id)

    async def _audio_cb(room, event):
        await audio_callback(room, event, client, bot_user_id)

    client.add_event_callback(_text_cb,  RoomMessageText)
    client.add_event_callback(_image_cb, RoomMessageImage)
    client.add_event_callback(_video_cb, RoomMessageVideo)
    client.add_event_callback(_file_cb,  RoomMessageFile)
    client.add_event_callback(_audio_cb, RoomMessageAudio)

    try:
        sync = await client.sync(timeout=30000)
        if isinstance(sync, SyncError):
            logger.error(f"Initial sync failed: {sync.message}")
            return
        logger.info("Initial sync complete")

        room_resp = await client.room_resolve_alias(room_id)
        if hasattr(room_resp, 'room_id'):
            resolved = room_resp.room_id
            join = await client.join(resolved)
            if hasattr(join, 'room_id'):
                room_id = join.room_id
                logger.info(f"Joined {room_id}")

        # Recover any sessions that survived a restart
        recovered = _db_load_sessions()
        for s in recovered:
            sessions[s.sender] = s
            logger.info(f"Recovered session for {s.sender}: {s.content_summary()}")
        if recovered:
            names = ", ".join(s.sender for s in recovered)
            await _send(client, room_id,
                f"Salty restarted — {len(recovered)} open session(s) recovered ({names}).\n"
                f"Say **salty done** to save or **salty cancel** to discard.")

        asyncio.create_task(autosave_loop(client, room_id, api_key))
        logger.info(f"Listening — autosave after {AUTOSAVE_MINUTES} min idle…")
        await client.sync_forever(timeout=30000, full_state=False)

    except KeyboardInterrupt:
        logger.info("Shutdown requested")
    finally:
        await client.close()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        sys.exit(0)
